version: '3.7'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  producer:
    build:
      context: ./producer
    depends_on:
      - kafka
      - mongodb
    ports:
      - "3005:3005"

  consumer:
    build:
      context: ./consumer
    depends_on:
      - kafka
      - mongodb
volumes:
  mongodb_data: